### ISSUE TITLE
Doesn't work when run on a not supported Python version

### ISSUE THREAD

**Issue by jul-star** [se2p/pynguin#40]
(env) D:\Projects\Python\PynguinTest>pynguin
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Projects\Python\PynguinTest\env\Scripts\pynguin.exe\__main__.py", line 4, in <module>
  File "D:\Projects\Python\PynguinTest\env\Lib\site-packages\pynguin\__init__.py", line 9, in <module>
    import pynguin.generator as gen
  File "D:\Projects\Python\PynguinTest\env\Lib\site-packages\pynguin\generator.py", line 31, in <module>
    import pynguin.analyses.seeding as seeding  # pylint: disable=consider-using-from-import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\Python\PynguinTest\env\Lib\site-packages\pynguin\analyses\seeding.py", line 25, in <module>
    import pynguin.ga.testcasechromosome as tcc
  File "D:\Projects\Python\PynguinTest\env\Lib\site-packages\pynguin\ga\testcasechromosome.py", line 13, in <module>
    import pynguin.ga.chromosome as chrom
  File "D:\Projects\Python\PynguinTest\env\Lib\site-packages\pynguin\ga\chromosome.py", line 13, in <module>
    import pynguin.ga.computations as ff
  File "D:\Projects\Python\PynguinTest\env\Lib\site-packages\pynguin\ga\computations.py", line 17, in <module>
    from pynguin.testcase.execution import ExecutionTrace
  File "D:\Projects\Python\PynguinTest\env\Lib\site-packages\pynguin\testcase\execution.py", line 425, in <module>
    class ExecutionTracer:
  File "D:\Projects\Python\PynguinTest\env\Lib\site-packages\pynguin\testcase\execution.py", line 460, in ExecutionTracer
    Compare.IN: lambda val1, val2: (
    ^^^^^^^^^^
  File "C:\Users\Jstar\AppData\Local\Programs\Python\Python311\Lib\enum.py", line 787, in __getattr__
    raise AttributeError(name) from None
AttributeError: IN

**Comment by stephanlukasczyk** [comment]
From what I see from the trace, you're trying to run Pynguin on Python 3.11. However, as stated in its read-me, Python 3.11 is not yet supported. Could you please try again with Python 3.10? Please also try to reproduce the steps from the documentation.
